insert into products (product_name, sellprice, buyprice) values ('Soup - Chicken And Wild Rice', 134, 101);
insert into products (product_name, sellprice, buyprice) values ('Caviar - Salmon', 126, 101);
insert into products (product_name, sellprice, buyprice) values ('Squid - U 5', 140, 111);
insert into products (product_name, sellprice, buyprice) values ('Cheese - Brie, Cups 125g', 126, 103);
insert into products (product_name, sellprice, buyprice) values ('Tomatoes - Hot House', 141, 112);
insert into products (product_name, sellprice, buyprice) values ('Table Cloth - 53x69 Colour', 147, 119);
insert into products (product_name, sellprice, buyprice) values ('Macaroons - Homestyle Two Bit', 145, 100);
insert into products (product_name, sellprice, buyprice) values ('Rabbit - Frozen', 130, 117);
insert into products (product_name, sellprice, buyprice) values ('Glaze - Apricot', 136, 102);
insert into products (product_name, sellprice, buyprice) values ('Flower - Leather Leaf Fern', 133, 108);
insert into products (product_name, sellprice, buyprice) values ('Nantucket Cranberry Juice', 136, 110);
insert into products (product_name, sellprice, buyprice) values ('Table Cloth 54x54 White', 150, 108);
insert into products (product_name, sellprice, buyprice) values ('Wine - Shiraz South Eastern', 126, 101);
insert into products (product_name, sellprice, buyprice) values ('Soup - Beef Conomme, Dry', 134, 107);
insert into products (product_name, sellprice, buyprice) values ('Cranberry Foccacia', 137, 118);
insert into products (product_name, sellprice, buyprice) values ('Bread - Onion Focaccia', 135, 107);
insert into products (product_name, sellprice, buyprice) values ('Cranberries - Dry', 129, 117);
insert into products (product_name, sellprice, buyprice) values ('Lamb - Pieces, Diced', 146, 116);
insert into products (product_name, sellprice, buyprice) values ('Mushroom - Enoki, Fresh', 141, 104);
insert into products (product_name, sellprice, buyprice) values ('Easy Off Oven Cleaner', 146, 108);
insert into products (product_name, sellprice, buyprice) values ('Ham - Procutinni', 131, 110);
insert into products (product_name, sellprice, buyprice) values ('Sausage - Meat', 129, 120);
insert into products (product_name, sellprice, buyprice) values ('Raisin - Golden', 139, 113);
insert into products (product_name, sellprice, buyprice) values ('Miso Paste White', 130, 120);
insert into products (product_name, sellprice, buyprice) values ('Cheese - Oka', 147, 101);
insert into products (product_name, sellprice, buyprice) values ('Cheese - Parmesan Cubes', 137, 115);
insert into products (product_name, sellprice, buyprice) values ('Southern Comfort', 146, 108);
insert into products (product_name, sellprice, buyprice) values ('Wine - Coteaux Du Tricastin Ac', 149, 114);
insert into products (product_name, sellprice, buyprice) values ('Cheese - Brie', 130, 111);
insert into products (product_name, sellprice, buyprice) values ('Cookies - Englishbay Oatmeal', 147, 116);
insert into products (product_name, sellprice, buyprice) values ('Wine - Prem Select Charddonany', 146, 113);
insert into products (product_name, sellprice, buyprice) values ('Sauce - Plum', 133, 100);
insert into products (product_name, sellprice, buyprice) values ('Potatoes - Idaho 100 Count', 132, 113);
insert into products (product_name, sellprice, buyprice) values ('Pork - Ham, Virginia', 132, 104);
insert into products (product_name, sellprice, buyprice) values ('Sesame Seed', 137, 107);
insert into products (product_name, sellprice, buyprice) values ('Shiro Miso', 149, 119);
insert into products (product_name, sellprice, buyprice) values ('Syrup - Monin - Blue Curacao', 136, 113);
insert into products (product_name, sellprice, buyprice) values ('Green Tea Refresher', 142, 111);
insert into products (product_name, sellprice, buyprice) values ('Sambuca Cream', 128, 113);
insert into products (product_name, sellprice, buyprice) values ('Nantucket - Kiwi Berry Cktl.', 134, 109);
insert into products (product_name, sellprice, buyprice) values ('Sage Derby', 128, 108);
insert into products (product_name, sellprice, buyprice) values ('Muffin Batt - Blueberry Passion', 127, 113);
insert into products (product_name, sellprice, buyprice) values ('Mix - Cocktail Strawberry Daiquiri', 128, 103);
insert into products (product_name, sellprice, buyprice) values ('Sauce - Vodka Blush', 130, 118);
insert into products (product_name, sellprice, buyprice) values ('Pork Loin Bine - In Frenched', 142, 106);
insert into products (product_name, sellprice, buyprice) values ('White Fish - Filets', 140, 117);
insert into products (product_name, sellprice, buyprice) values ('Cucumber - Pickling Ontario', 139, 114);
insert into products (product_name, sellprice, buyprice) values ('Cookies - Englishbay Wht', 136, 103);
insert into products (product_name, sellprice, buyprice) values ('Bonito Flakes - Toku Katsuo', 128, 105);
insert into products (product_name, sellprice, buyprice) values ('Wine - Rioja Campo Viejo', 148, 103);
insert into products (product_name, sellprice, buyprice) values ('Cheese - Mascarpone', 133, 100);
insert into products (product_name, sellprice, buyprice) values ('Vegetable - Base', 127, 102);
insert into products (product_name, sellprice, buyprice) values ('Juice - Apple 284ml', 147, 104);
insert into products (product_name, sellprice, buyprice) values ('Bagel - Everything Presliced', 149, 114);
insert into products (product_name, sellprice, buyprice) values ('Soupcontfoam16oz 116con', 142, 106);
insert into products (product_name, sellprice, buyprice) values ('Bread - Roll, Canadian Dinner', 125, 104);
insert into products (product_name, sellprice, buyprice) values ('Beef - Salted', 140, 115);
insert into products (product_name, sellprice, buyprice) values ('Bread - Raisin Walnut Pull', 150, 103);
insert into products (product_name, sellprice, buyprice) values ('Contreau', 138, 108);
insert into products (product_name, sellprice, buyprice) values ('Crackers - Melba Toast', 135, 111);
insert into products (product_name, sellprice, buyprice) values ('Coconut - Creamed, Pure', 135, 115);
insert into products (product_name, sellprice, buyprice) values ('Wasabi Powder', 130, 103);
insert into products (product_name, sellprice, buyprice) values ('Wine - White, Schroder And Schyl', 150, 100);
insert into products (product_name, sellprice, buyprice) values ('Crab Brie In Phyllo', 131, 116);
insert into products (product_name, sellprice, buyprice) values ('Nut - Almond, Blanched, Sliced', 144, 104);
insert into products (product_name, sellprice, buyprice) values ('Lamb - Leg, Boneless', 133, 107);
insert into products (product_name, sellprice, buyprice) values ('Beef - Short Ribs', 127, 105);
insert into products (product_name, sellprice, buyprice) values ('Crab - Meat Combo', 143, 115);
insert into products (product_name, sellprice, buyprice) values ('Rhubarb', 133, 109);
insert into products (product_name, sellprice, buyprice) values ('Cheese Cloth', 138, 117);
insert into products (product_name, sellprice, buyprice) values ('Soup - Campbells Bean Medley', 138, 105);
insert into products (product_name, sellprice, buyprice) values ('Club Soda - Schweppes, 355 Ml', 129, 100);
insert into products (product_name, sellprice, buyprice) values ('Beans - Kidney, Canned', 146, 107);
insert into products (product_name, sellprice, buyprice) values ('Flower - Carnations', 150, 100);
insert into products (product_name, sellprice, buyprice) values ('Bread Base - Toscano', 128, 111);
insert into products (product_name, sellprice, buyprice) values ('Coke - Classic, 355 Ml', 141, 119);
insert into products (product_name, sellprice, buyprice) values ('Pastry - Plain Baked Croissant', 149, 112);
insert into products (product_name, sellprice, buyprice) values ('Longos - Chicken Cordon Bleu', 147, 104);
insert into products (product_name, sellprice, buyprice) values ('Lamb - Shoulder, Boneless', 147, 100);
insert into products (product_name, sellprice, buyprice) values ('Ecolab - Medallion', 150, 113);
insert into products (product_name, sellprice, buyprice) values ('Cheese - St. Paulin', 149, 115);
insert into products (product_name, sellprice, buyprice) values ('Fish - Artic Char, Cold Smoked', 147, 106);
insert into products (product_name, sellprice, buyprice) values ('Asparagus - White, Canned', 148, 111);
insert into products (product_name, sellprice, buyprice) values ('Garbage Bag - Clear', 146, 109);
insert into products (product_name, sellprice, buyprice) values ('Oysters - Smoked', 141, 112);
insert into products (product_name, sellprice, buyprice) values ('Piping - Bags Quizna', 144, 107);
insert into products (product_name, sellprice, buyprice) values ('Sauce Bbq Smokey', 148, 118);
insert into products (product_name, sellprice, buyprice) values ('Beef - Flank Steak', 142, 115);
insert into products (product_name, sellprice, buyprice) values ('Cheese - Cheddar, Mild', 133, 113);
insert into products (product_name, sellprice, buyprice) values ('Bread - Kimel Stick Poly', 150, 116);
insert into products (product_name, sellprice, buyprice) values ('Bread - White Mini Epi', 134, 105);
insert into products (product_name, sellprice, buyprice) values ('Tumeric', 128, 114);
insert into products (product_name, sellprice, buyprice) values ('Coffee - Almond Amaretto', 133, 116);
insert into products (product_name, sellprice, buyprice) values ('Mix - Cappucino Cocktail', 140, 112);
insert into products (product_name, sellprice, buyprice) values ('Lychee', 136, 114);
insert into products (product_name, sellprice, buyprice) values ('Shark - Loin', 133, 120);
insert into products (product_name, sellprice, buyprice) values ('Soup - Campbells Mushroom', 133, 113);
insert into products (product_name, sellprice, buyprice) values ('Chick Peas - Dried', 126, 117);
insert into products (product_name, sellprice, buyprice) values ('Oneshot Automatic Soap System', 132, 108);
insert into products (product_name, sellprice, buyprice) values ('Crackers - Trio', 130, 105);
